function(set_project_warnings target_name)
    if(MSVC)
        target_compile_options(${target_name} INTERFACE /W4)
    else()
        target_compile_options(${target_name} INTERFACE -Wall -Wextra -Wpedantic)
    endif()
endfunction()
